services:
  kong:
    image: kong:3.9.1

    command: kong start

    networks:
      - chat-net
    depends_on:
      - server
    ports:
      - ${SERVER_PORT}:8000
      - ${API_GATEWAY_ADMIN_PORT}:8001

    volumes:
      - ./kong/kong.conf:/etc/kong/kong.conf
      - ./kong/kong.yml:/kong/kong.yml
      - ./kong/plugins:/kong/plugins:ro

  konga:
    image: pantsel/konga:latest

    networks:
      - chat-net
    depends_on:
      - kong
    ports:
      - ${API_GATEWAY_UI_PORT}:1337

    environment:
      - NODE_ENV=development
      - KONGA_SEED_USER_DATA_SOURCE_FILE=/app/seeds/user_seed.json
      - KONGA_SEED_KONG_NODE_DATA_SOURCE_FILE=/app/seeds/kong_node_seed.json
    volumes:
      - ./kong/konga/seeds:/app/seeds
      - konga-data:/data

volumes:
  konga-data:
    driver: local
